# Data Maths
## Vector Operations

In [ ]:
import numpy as np

# Creating vectors
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])

# Vector addition
vector_addition_result = vector_a + vector_b
print(vector_addition_result)  # Output: [5 7 9]


[5 7 9]


In [ ]:
# Vector subtraction
vector_subtraction_result = vector_a - vector_b
print(vector_subtraction_result)  # Output: [-3 -3 -3]

[-3 -3 -3]


In [ ]:
# Scalar multiplication of a vector
scalar = 2
scalar_multiplication_result = scalar * vector_a
print(scalar_multiplication_result)  # Output: [2 4 6]

[2 4 6]


In [ ]:
# Dot product of two vectors
dot_product_result = np.dot(vector_a, vector_b)
print(dot_product_result)  # Output: 32

32


In [ ]:
# Cross product of two vectors (for 3D vectors)
cross_product_result = np.cross(vector_a, vector_b)
print(cross_product_result)  # Output: [-3  6 -3]

[-3  6 -3]


## Matrix Operations

In [ ]:
# Create a matrix from a nested list
matrix_a = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 2, 9]])

matrix_b = np.array([[9, 8, 7],
                     [6, 5, 4],
                     [3, 2, 1]])


# Matrix addition
matrix_addition_result = matrix_a + matrix_b
print("Matrix Addition:\n", matrix_addition_result)

Matrix Addition:
 [[10 10 10]
 [10 10 10]
 [10  4 10]]


In [ ]:
# Matrix subtraction
matrix_subtraction_result = matrix_a - matrix_b
print("Matrix Subtraction:\n", matrix_subtraction_result)

Matrix Subtraction:
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  0  8]]


In [ ]:
# Scalar multiplication of a matrix
scalar = 2
scalar_multiplication_result = scalar * matrix_a
print("Scalar Multiplication:\n", scalar_multiplication_result)

Scalar Multiplication:
 [[ 2  4  6]
 [ 8 10 12]
 [14  4 18]]


In [ ]:
# Element-wise multiplication of two matrices
elementwise_multiplication_result = np.multiply(matrix_a, matrix_b)
print("Element-wise Multiplication:\n", elementwise_multiplication_result)

Element-wise Multiplication:
 [[ 9 16 21]
 [24 25 24]
 [21  4  9]]


In [ ]:
# Matrix multiplication (dot product)
matrix_c = np.array([[1, 2],
                     [3, 4],
                     [5, 6]])

matrix_multiplication_result = np.dot(matrix_a, matrix_c)
print("Matrix Multiplication (Dot Product):\n", matrix_multiplication_result)

Matrix Multiplication (Dot Product):
 [[22 28]
 [49 64]
 [58 76]]


In [ ]:
# Transpose of a matrix
matrix_transpose = np.transpose(matrix_a)
print("Transpose of Matrix A:\n", matrix_transpose)

Transpose of Matrix A:
 [[1 4 7]
 [2 5 2]
 [3 6 9]]


In [ ]:
# Determinant of a matrix
matrix_determinant = np.linalg.det(matrix_a)
print("Determinant of Matrix A:", matrix_determinant)

Determinant of Matrix A: -36.0


In [ ]:
# Inverse of a matrix
matrix_inverse = np.linalg.inv(matrix_a)
print("Inverse of Matrix A:\n", matrix_inverse)

Inverse of Matrix A:
 [[-0.91666667  0.33333333  0.08333333]
 [-0.16666667  0.33333333 -0.16666667]
 [ 0.75       -0.33333333  0.08333333]]


## Probability

In [ ]:
# Probabilities
P_S = 3 / 12  # Probability of selecting a strawberry doughnut
P_C = 5 / 12  # Probability of selecting a chocolate doughnut

# Probability of selecting either a strawberry doughnut or a chocolate doughnut
P_S_or_C = P_S + P_C
print("Probability of selecting either a strawberry doughnut or a chocolate doughnut:", P_S_or_C)



Probability of selecting either a strawberry doughnut or a chocolate doughnut: 0.6666666666666667


In [ ]:
# Given data
n_students_total = 3000
n_students_S = 1232
n_students_F = 879
n_students_R = 114
n_students_S_and_F = 103
n_students_S_and_R = 23
n_students_F_and_R = 14
n_students_S_and_F_and_R = 7

# Probabilities
P_S = n_students_S / n_students_total
P_F = n_students_F / n_students_total
P_R = n_students_R / n_students_total
P_S_and_F = n_students_S_and_F / n_students_total
P_S_and_R = n_students_S_and_R / n_students_total
P_F_and_R = n_students_F_and_R / n_students_total
P_S_and_F_and_R = n_students_S_and_F_and_R / n_students_total

# Probability of the union of events
P_union = P_S + P_F + P_R - P_S_and_F - P_S_and_R - P_F_and_R + P_S_and_F_and_R
print("Probability of taking at least one of French, Spanish, or Russian course:", P_union)


Probability of taking at least one of French, Spanish, or Russian course: 0.6973333333333332


In [ ]:
# Given data
P_defective = 0.06
P_not_defective = 1 - P_defective
n_automobiles = 5

# Probability of none of the automobiles having defective brakes
P_none_defective = P_not_defective ** n_automobiles

# Probability of at least one automobile having defective brakes
P_at_least_one_defective = 1 - P_none_defective
print("Probability of at least one automobile having defective brakes:", P_at_least_one_defective)

Probability of at least one automobile having defective brakes: 0.26609597760000026


In [ ]:
# Given data
P_B1 = 3/8  # Probability of selecting a black chip on the first draw
P_B1_and_W2 = 15/56  # Probability of selecting a black chip and a white chip

# Probability of selecting a white chip on the second draw given that the first chip selected was a black chip
P_W2_given_B1 = P_B1_and_W2 / P_B1
print("Probability of selecting a white chip on the second draw given that the first chip selected was a black chip:", P_W2_given_B1)

Probability of selecting a white chip on the second draw given that the first chip selected was a black chip: 0.7142857142857143


In [ ]:
# Given data
P_D = 0.005  # Probability of a person having the disease
P_not_D = 1 - P_D  # Probability of a person not having the disease
P_P_given_D = 0.99  # Probability of a positive signal given that the person has the disease
P_P_given_not_D = 0.01  # Probability of a positive signal given that the person does not have the disease

# Calculating the probability of a positive signal
P_P = P_P_given_D * P_D + P_P_given_not_D * P_not_D

# Calculating the probability that the person actually has the disease given a positive signal
P_D_given_P = (P_P_given_D * P_D) / P_P
print("Probability that the person actually has the disease given a positive signal:", P_D_given_P)

Probability that the person actually has the disease given a positive signal: 0.33221476510067116
